// POST /users

import { Prisma } from "@prisma/client";
import { RequestHandler } from "express";
import { Services, ArweaveSignatureTags, DocType } from "../types";
import { AddUserRequest, AddUserResponse } from "../common/server-api";

// TODO: add location
// TODO: add local time night vs. day
export function addUser({ prisma, arweave }: Services): RequestHandler {
  return async (req, res) => {
    const { walletId, name, twitterUsername, signature } =
      req.body as AddUserRequest;

    // TODO: validate request, maybe use autogenerated zod

    try {
      const result = await prisma.user.create({
        data: {
          id: walletId,
          name,
          twitterUsername,
          signature,
        },
      });
      // add to arweave
      // TODO: fill in essayRef from request
      console.log("");
      const doc = await arweave.addDocument(walletId, result, {
        ...result,
        walletId: result.id,
        docType: DocType.Signature,
        essayRef: "tx123",
      } as ArweaveSignatureTags as any);
      console.log(doc);

      // store new document in the database with user?
      await prisma.user.update({
        where: { id: walletId },
        data: { transactionId: doc.txID },
      });

      res.json({ ...result, walletId: result.id } as AddUserResponse);
    } catch (err) {
      console.log(err);
      if (err instanceof Prisma.PrismaClientValidationError) {
        res
          .status(400)
          .json({ error: `Received invalid data. ${err.message}` });
        return;
      }
      res.status(400).json({ error: err.message });
    }
  };
}
