// GET /contributions

import { Prisma } from "@prisma/client";
import { RequestHandler } from "express";
import { Services } from "../types";
import { GetContributionsRequest, Contribution } from "../common/server-api";

const Limit = 500;

// Optional fields in body: content
export function getContributions({ prisma }: Services): RequestHandler {
  return async (req, res) => {
    try {
      const { offset = 0, contributionId } =
        req.query as GetContributionsRequest;

      // TODO: validate request, maybe use autogenerated zod
      const contributions = [];
      if (contributionId) {
        const highlightedContribution = await prisma.contribution.findFirst({
          where: { id: contributionId },
          include: {
            author: true,
          },
        });
        contributions.push(highlightedContribution);
      }

      const storageContributions = await prisma.contribution.findMany({
        where: { id: contributionId ? contributionId : undefined },
        orderBy: { createdAt: "asc" },
        include: {
          author: true,
        },
        skip: offset,
        take: Limit,
      });

      contributions.push(...storageContributions);

      res.status(200).json(
        contributions.map((contribution) => ({
          ...contribution,
          author: {
            ...contribution.author,
            walletId: contribution.author.id,
          },
        })) as Contribution[]
      );
    } catch (err) {
      console.log(err);
      if (err instanceof Prisma.PrismaClientValidationError) {
        res.status(400).json({ error: "Received invalid data." });
        return;
      }
      res.status(400).json({ error: err.message });
    }
  };
}
